# Выполнить:
#
# - Создаем каталог с данными, ключами и конфигами серверной части - ./data
# - Создаем каталог для логов - ./logs

# 1. docker-compose pull
#
# 2. docker-compose run --rm openvpn ovpn_genconfig -u udp://localhost
#    где localhost - хост на который будут стучаться клиенты
#
# 3. docker run -v "./data:/etc/openvpn" --rm -it kylemanna/openvpn ovpn_initpki
#    генерирует серверный сертификат. Запросит пароль - ввести его и записать где-то, он нужен для генерации клиентских сертификатов
#
# 4. docker run -v "./data:/etc/openvpn" --rm -it kylemanna/openvpn easyrsa build-client-full CLIENTNAME nopass
#    где CLIENTNAME имя клиента, для которого делаем клиентский сертификат
#
# 5. docker run -v "./data:/etc/openvpn" --rm kylemanna/openvpn ovpn_getclient CLIENTNAME > CLIENTNAME.ovpn
#    где CLIENTNAME имя клиента, для кторого сделали сертификат до этого и хотим получить конфиг файл

version: '3'

services:
  openvpn:
    container_name: openvpn
    image: kylemanna/openvpn
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    volumes:
      - "./data:/etc/openvpn"
      - "./logs:/tmp/"
    ports:
      - "1194:1194/udp"
