version: "3.6"

services:
  mail2telegram:
    container_name: mail2telegram
    build:
      context: mail2telegram
    image: "mail2telegram"
    restart: always
    environment:
      - "CHAT_ID=XXXXX"                  # Telegram Chat ID
      - "BOT_ID=botXXXXXXXXX:XXXXXXXX"   # Telegram Bot ID
    volumes:
      - "/root/logs:/root/logs"
